// lang.js - با پشتیبانی از 6 زبان

const content = { en: { aboutTitle: "About LYNX", aboutText: "LYNX is a visionary blockchain project designed to revolutionize how we communicate in the decentralized world...", roadmapTitle: "Project Roadmap", contactTitle: "Contact Us", contactDesc: "If you have any questions or suggestions, feel free to reach out to us. We are here to help and collaborate!", contactName: "Name", contactEmail: "Email", contactMessage: "Message", contactButton: "Send Message" }, fa: { aboutTitle: "درباره لاینکس", aboutText: "لاینکس یک پروژه نوآورانه بلاک‌چینی است که برای تحول در شیوه‌های ارتباط غیرمتمرکز طراحی شده است...", roadmapTitle: "نقشه راه پروژه", contactTitle: "تماس با ما", contactDesc: "اگر سؤال یا پیشنهادی دارید، خوشحال می‌شویم با ما در تماس باشید. ما اینجا هستیم برای همکاری!", contactName: "نام", contactEmail: "ایمیل", contactMessage: "پیام", contactButton: "ارسال پیام" }, zh: { aboutTitle: "关于 LYNX", aboutText: "LYNX 是一个前瞻性的区块链项目，旨在革新去中心化世界的通信方式...", roadmapTitle: "项目路线图", contactTitle: "联系我们", contactDesc: "如果您有任何问题或建议，欢迎与我们联系。我们愿意帮助并合作！", contactName: "姓名", contactEmail: "电子邮件", contactMessage: "信息", contactButton: "发送消息" }, ru: { aboutTitle: "О LYNX", aboutText: "LYNX — это передовой блокчейн-проект, созданный для революции в сфере децентрализованной связи...", roadmapTitle: "Дорожная карта проекта", contactTitle: "Свяжитесь с нами", contactDesc: "Если у вас есть вопросы или предложения, свяжитесь с нами. Мы готовы помочь и сотрудничать!", contactName: "Имя", contactEmail: "Эл. почта", contactMessage: "Сообщение", contactButton: "Отправить сообщение" }, tr: { aboutTitle: "LYNX Hakkında", aboutText: "LYNX, merkeziyetsiz dünyada iletişimi yeniden tanımlamayı amaçlayan yenilikçi bir blockchain projesidir...", roadmapTitle: "Proje Yol Haritası", contactTitle: "Bize Ulaşın", contactDesc: "Herhangi bir sorunuz veya öneriniz varsa, bizimle iletişime geçmekten çekinmeyin. Yardımcı olmaya hazırız!", contactName: "İsim", contactEmail: "E-posta", contactMessage: "Mesaj", contactButton: "Mesaj Gönder" }, ar: { aboutTitle: "حول LYNX", aboutText: "LYNX هو مشروع بلوكشين مبتكر يهدف إلى إحداث ثورة في كيفية التواصل في العالم اللامركزي...", roadmapTitle: "خارطة طريق المشروع", contactTitle: "اتصل بنا", contactDesc: "إذا كانت لديك أي أسئلة أو اقتراحات، فلا تتردد في التواصل معنا. نحن هنا للمساعدة والتعاون!", contactName: "الاسم", contactEmail: "البريد الإلكتروني", contactMessage: "الرسالة", contactButton: "إرسال الرسالة" } };

const lang = localStorage.getItem("lynx-lang") || "en";

function translatePage() { const t = content[lang]; if (document.getElementById("about-title")) document.getElementById("about-title").innerText = t.aboutTitle; if (document.getElementById("about-text")) document.getElementById("about-text").innerText = t.aboutText; if (document.getElementById("roadmap-title")) document.getElementById("roadmap-title").innerText = t.roadmapTitle; if (document.getElementById("contact-title")) document.getElementById("contact-title").innerText = t.contactTitle; if (document.getElementById("contact-desc")) document.getElementById("contact-desc").innerText = t.contactDesc; if (document.getElementById("label-name")) document.getElementById("label-name").innerText = t.contactName; if (document.getElementById("label-email")) document.getElementById("label-email").innerText = t.contactEmail; if (document.getElementById("label-message")) document.getElementById("label-message").innerText = t.contactMessage; if (document.getElementById("send-btn")) document.getElementById("send-btn").innerText = t.contactButton; }

document.addEventListener("DOMContentLoaded", translatePage);

